language: java
# speed up travis with repo caching https://docs.travis-ci.com/user/caching/
cache:
  directories:
    - $HOME/.m2

#using jobs instead
#install: mvn install -DskipTests=true -Dgpg.skip=true -B -q

jdk:
  - openjdk8
#  - openjdk10
#  - openjdk11

jobs:
  include:

    # compile check is fast
    - stage: "fast compile check"
      install: mvn test-compile -DskipTests=true -Dgpg.skip=true -B -V
      script: mvn test -Pquickrun -Dcheckstyle.skip=true -Dgpg.skip=true -B -V
    # verify
    - stage: "slow verify site"
      install: mvn test-compile -DskipTests=true -Dgpg.skip=true -B -V
      script: mvn verify site -B -V
    - stage: "examples projects all"
      install: mvn test-compile -Pquickrun,all -Dcheckstyle.skip=true -DskipTests=true -Dgpg.skip=true -B -V
      script: mvn verify -Pquickrun,all site -B -V
    - stage: "java11 build verify"
      if: "branch =~ ^java11.*"
      jdk: openjdk11
      install: mvn test-compile -DskipTests=true -Dgpg.skip=true -B -V
      script: mvn verify site -B -V
    - stage: "java11 examples projects all"
      if: "branch =~ ^java11.*"
      jdk: openjdk11
      install: mvn test-compile -Pquickrun,all -Dcheckstyle.skip=true -DskipTests=true -Dgpg.skip=true -B -V
      script: mvn verify -Pquickrun,all site -B -V

