version: '3'

services:
  wildfly10:
    #image: jboss/wildfly:10.0.0.Final
    build:
      context: ./.docker
      dockerfile: Dockerfile-wildfly10-aquil
    networks:
      - default
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:9990:9990
    command: []
    volumes:
      #- ./.docker/deployments/:/opt/jboss/wildfly/standalone/deployments/ #copy files here to deploy
      - .:/data
      - ~/.m2:/opt/jboss/.m2
#      - ./.docker/wildfly10/:/opt/jboss/wildfly/ #export home, cant do as it is then empty
      #- ./.docker/logs:/opt/jboss/wildfly/standalone/logs/ #surface logs if you want