# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

shared: &shared
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - jboss-seam-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - jboss-seam-

      # run tests!
      - run: mvn test-compile
      # run tests!
      - run: mvn verify

      - save_cache:
          paths:
            - ~/.m2
          key: jboss-seam-{{ checksum "pom.xml" }}

# Specify service dependencies here if necessary
# CircleCI maintains a library of pre-built images
# documented at https://circleci.com/docs/2.0/circleci-images/

jobs:
  jdk8:
    <<: *shared
    docker:
      - image: circleci/openjdk:8-jdk
  jdk11:
    <<: *shared
    docker:
      - image: circleci/openjdk:11-jdk

workflows:
  version: 2
  work:
    jobs:
      - jdk8
      - jdk11