FROM jboss/wildfly:10.1.0.Final

# User root user to install software
USER root

# Install necessary packages
RUN yum -y install maven && yum clean all

RUN mkdir /data

# Switch back to jboss user
USER jboss

RUN /opt/jboss/wildfly/bin/add-user.sh "admin" "Admin#70365" --silent

RUN sed -i \
        -e 's|\(<https-listener\)|<ajp-listener name="ajp" socket-binding="ajp" scheme="http" enabled="true"/>\1|' \
        -e 's|^<subsystem xmlns="urn:jboss:domain:weld:3.0"/>|<subsystem xmlns="urn:jboss:domain:weld:3.0" require-bean-descriptor="true"/>|' \
        /opt/jboss/wildfly/standalone/configuration/standalone.xml

ENV JBOSS_HOME_TEST /opt/jboss/wildfly/


WORKDIR "/data/"

CMD ["mvn", "verify", "-Dcheckstyle.skip=true", "-Dgpg.skip=true", "-B", "-V", "-Pquickrun,integration-test", "-rf", ":seam-integration-tests"]